services:
  feeds-site-builder:
    build: .
    container_name: feeds-blog-app
    restart: no
    volumes:
      - ./feeds.code-drill.eu:/app/feeds.code-drill.eu
#      - .:/app
      # Mount git config (Linux/Mac)
#      - ~/.ssh:/root/.ssh:ro
#      - ~/.gitconfig:/root/.gitconfig:ro
      # For Windows users, uncomment the following lines instead:
      - ${USERPROFILE}/.ssh:/root/.ssh:ro
      - ${USERPROFILE}/.gitconfig:/root/.gitconfig:ro
    environment:
      - PYTHONPATH=/app:.
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
