[project]
name = "feeds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "nikola[extras]>=8.3.3",
    "requests>=2.31.0",
    "typer>=0.12.0",
]
